"""Render the panel's output into a styled HTML memo.

The MoA aggregator emits loosely-formatted text (===== rules, ALL-CAPS section
titles, "N) Clause" headings, "Label:" fields). normalize_to_markdown() coerces
that into clean Markdown; render_html() wraps it in a print-quality template.
"""

import re
from pathlib import Path

import markdown

_LABELS = ("quote", "favours", "favors", "severity", "why it matters", "why",
           "redline", "issue", "impact", "risk", "recommendation")


def normalize_to_markdown(text: str) -> str:
    out = []
    for raw in text.splitlines():
        s = raw.strip()
        if re.fullmatch(r"[=_*\-–—]{3,}", s):                  # horizontal rule → drop
            continue
        if not s:
            out.append("")
            continue
        # Already a Markdown heading/quote/list — keep, but promote a numbered
        # clause line that carries a clause reference to a ### heading.
        if re.match(r"^(#{1,6}\s|>\s|[-*]\s|\d+[.)]\s)", s) and not s.isupper():
            m = re.match(r"^(\d+)[.)]\s+(.*)", s)
            if m and ("—" in s or "Cl" in s or m.group(2)[:40].isupper()):
                out.append(f"### {m.group(1)}. {m.group(2)}")
            else:
                out.append(raw)
            continue
        low = s.lower()
        label = next((l for l in _LABELS if low.startswith(l + ":") or low.startswith(l + " -")), None)
        if label:
            rest = s[s.find(":") + 1:].strip() if ":" in s else s[len(label):].lstrip(" -").strip()
            out.append(f"> {rest}" if label == "quote" else f"- **{label.title()}:** {rest}")
            continue
        # ALL-CAPS standalone line → section heading (# for the first, else ##).
        if re.search(r"[A-Za-z]", s) and s.upper() == s and len(s) < 70:
            title = s.title().replace("Cl ", "Cl. ")
            out.append(("# " if not any(x.startswith("#") for x in out) else "## ") + title)
            continue
        # "N) ALLCAPS TITLE — Cl X" clause heading not caught above.
        m = re.match(r"^(\d+)[.)]\s+(.*)", s)
        if m and (m.group(2)[:40].isupper() or "—" in s or "Cl" in s):
            out.append(f"### {m.group(1)}. {m.group(2)}")
            continue
        out.append(raw)
    return "\n".join(out)


def render_html(text: str, out_path: Path, title: str) -> None:
    body = markdown.markdown(normalize_to_markdown(text),
                             extensions=["tables", "fenced_code", "sane_lists"])
    out_path.write_text(_TEMPLATE.format(title=title, body=body), encoding="utf-8")


_TEMPLATE = """<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title}</title>
<style>
  :root {{ color-scheme: light; }}
  body {{ margin: 0; background: #f4f4f5; color: #1c1c1e;
          font: 16px/1.65 -apple-system, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; }}
  main {{ max-width: 820px; margin: 0 auto; padding: 56px 28px 96px;
          background: #fff; min-height: 100vh; box-shadow: 0 1px 40px rgba(0,0,0,.06); }}
  h1 {{ font-size: 1.7rem; margin: 0 0 .2em; letter-spacing: -.01em; }}
  h2 {{ font-size: 1.25rem; margin: 2em 0 .5em; padding-top: .6em;
        border-top: 1px solid #ececec; }}
  h3 {{ font-size: 1.05rem; margin: 1.6em 0 .4em; }}
  p, li {{ color: #2a2a2e; }}
  code {{ background: #f1f1f3; padding: .12em .35em; border-radius: 4px; font-size: .9em; }}
  blockquote {{ margin: 1em 0; padding: .4em 1em; border-left: 3px solid #d4af37;
                background: #fbfaf5; color: #444; }}
  table {{ border-collapse: collapse; width: 100%; margin: 1em 0; font-size: .94em; }}
  th, td {{ border: 1px solid #e6e6e6; padding: .5em .7em; text-align: left; vertical-align: top; }}
  th {{ background: #faf9f7; }}
  strong {{ color: #111; }}
  .meta {{ color: #8a8a8e; font-size: .85rem; margin-bottom: 2em; }}
</style></head>
<body><main>
<p class="meta">Generated by the Hermes MoA × Unsiloed contract-risk panel</p>
{body}
</main></body></html>"""