import type { CardDefinition } from "./types.js";

// The full Arcane Towers card roster. This is the single source of truth for
// every stat used by both the server simulation and the client UI/renderer —
// nothing here is duplicated or re-declared anywhere else in the codebase.
export const CARD_DEFINITIONS: CardDefinition[] = [
  {
    id: "glimmer-sprite",
    name: "Glimmer Sprite",
    description: "A quick, cheap skirmisher. Great for cycling or chipping at a push.",
    cost: 2,
    rarity: "common",
    category: "troop",
    visual: { shape: "triangle", primaryColor: "#34d399", secondaryColor: "#047857" },
    unit: {
      health: 120,
      damage: 26,
      attackRange: 0.8,
      attackSpeedMs: 800,
      moveSpeed: 2.6,
      spawnCount: 1,
      targeting: "any",
      stationary: false,
      sightRange: 5,
      hitboxRadius: 0.35,
    },
  },
  {
    id: "kestrel-swarm",
    name: "Kestrel Swarm",
    description: "Three shrieking flyers-in-spirit. Fragile alone, dangerous together.",
    cost: 2,
    rarity: "common",
    category: "troop",
    visual: { shape: "dotCluster", primaryColor: "#fbbf24", secondaryColor: "#b45309" },
    unit: {
      health: 75,
      damage: 28,
      attackRange: 0.7,
      attackSpeedMs: 900,
      moveSpeed: 2.8,
      spawnCount: 3,
      targeting: "any",
      stationary: false,
      sightRange: 5,
      hitboxRadius: 0.3,
    },
  },
  {
    id: "blade-acolyte",
    name: "Blade Acolyte",
    description: "A dependable melee fighter that holds the line and trades blows.",
    cost: 3,
    rarity: "common",
    category: "troop",
    visual: { shape: "blade", primaryColor: "#cbd5e1", secondaryColor: "#475569" },
    unit: {
      health: 340,
      damage: 58,
      attackRange: 0.9,
      attackSpeedMs: 1100,
      moveSpeed: 1.8,
      spawnCount: 1,
      targeting: "any",
      stationary: false,
      sightRange: 5.5,
      hitboxRadius: 0.42,
    },
  },
  {
    id: "sparkfletcher",
    name: "Sparkfletcher",
    description: "Keen-eyed archer who picks off targets from well outside their reach.",
    cost: 3,
    rarity: "common",
    category: "troop",
    visual: { shape: "diamond", primaryColor: "#5eead4", secondaryColor: "#0f766e" },
    unit: {
      health: 170,
      damage: 42,
      attackRange: 4.5,
      attackSpeedMs: 1200,
      moveSpeed: 1.7,
      spawnCount: 1,
      targeting: "any",
      stationary: false,
      projectileSpeed: 9,
      sightRange: 6,
      hitboxRadius: 0.35,
    },
  },
  {
    id: "bulwark-spire",
    name: "Bulwark Spire",
    description: "A stationary defensive tower that pounds approaching ground troops.",
    cost: 4,
    rarity: "common",
    category: "troop",
    visual: { shape: "spire", primaryColor: "#d6d3d1", secondaryColor: "#57534e" },
    unit: {
      health: 560,
      damage: 50,
      attackRange: 3.2,
      attackSpeedMs: 1000,
      moveSpeed: 0,
      spawnCount: 1,
      targeting: "any",
      stationary: true,
      projectileSpeed: 8,
      sightRange: 5,
      hitboxRadius: 0.55,
    },
  },
  {
    id: "emberlobbers",
    name: "Emberlobbers",
    description: "Hurls molten shells that burst into splash damage on impact.",
    cost: 4,
    rarity: "rare",
    category: "troop",
    visual: { shape: "orb", primaryColor: "#fb923c", secondaryColor: "#9a3412" },
    unit: {
      health: 230,
      damage: 38,
      attackRange: 3.6,
      attackSpeedMs: 1600,
      moveSpeed: 1.5,
      spawnCount: 1,
      targeting: "any",
      stationary: false,
      splashRadius: 1.5,
      projectileSpeed: 6.5,
      sightRange: 5.5,
      hitboxRadius: 0.4,
    },
  },
  {
    id: "frostveil-mist",
    name: "Frostveil Mist",
    description: "A shard of ice that chips enemies and chills everything it touches.",
    cost: 2,
    rarity: "rare",
    category: "spell",
    visual: { shape: "bolt", primaryColor: "#7dd3fc", secondaryColor: "#0369a1" },
    spell: {
      radius: 2.4,
      damage: 90,
      towerDamageMultiplier: 0.35,
      slowFactor: 0.5,
      slowDurationMs: 4000,
    },
  },
  {
    id: "stone-golem",
    name: "Stone Golem",
    description: "A living mountain. Ignores enemy troops and marches straight for towers.",
    cost: 5,
    rarity: "epic",
    category: "troop",
    visual: { shape: "hexagon", primaryColor: "#ca8a04", secondaryColor: "#713f12" },
    unit: {
      health: 950,
      damage: 85,
      attackRange: 1.0,
      attackSpeedMs: 1500,
      moveSpeed: 1.1,
      spawnCount: 1,
      targeting: "buildingsOnly",
      stationary: false,
      sightRange: 7,
      hitboxRadius: 0.6,
    },
  },
  {
    id: "cataclysm-bolt",
    name: "Cataclysm Bolt",
    description: "Scorches an area outright. Devastating against clustered troops.",
    cost: 4,
    rarity: "epic",
    category: "spell",
    visual: { shape: "orb", primaryColor: "#c084fc", secondaryColor: "#6b21a8" },
    spell: {
      radius: 2.2,
      damage: 260,
      towerDamageMultiplier: 0.4,
    },
  },
  {
    id: "ironclad-vanguard",
    name: "Ironclad Vanguard",
    description: "A heavily armored champion who shrugs off hits and swings hard.",
    cost: 6,
    rarity: "legendary",
    category: "troop",
    visual: { shape: "colossus", primaryColor: "#fca5a5", secondaryColor: "#991b1b" },
    unit: {
      health: 1150,
      damage: 95,
      attackRange: 1.0,
      attackSpeedMs: 1400,
      moveSpeed: 1.3,
      spawnCount: 1,
      targeting: "any",
      stationary: false,
      sightRange: 5.5,
      hitboxRadius: 0.5,
    },
  },
];

const CARD_BY_ID = new Map(CARD_DEFINITIONS.map((card) => [card.id, card]));

export function getCardById(cardId: string): CardDefinition | undefined {
  return CARD_BY_ID.get(cardId);
}

export function isValidCardId(cardId: string): boolean {
  return CARD_BY_ID.has(cardId);
}
